services:
  - type: web
    name: sharepoint-flask-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envGroups:
      - flask-email
